@startuml Instrument
title Instrument
interface Instrument
{
    +play()
}
interface ElectronicInstrument
{
    +tune()
}
interface KeyboardInstrument
{
    +tune()
}
class Guitar
{
    +play()
}
class Piano
{
    +play()
}
class Orchestra
{
    -instrument:Instrument[]
    +playAll()
}
Guitar .up-|> Instrument : <<implements>>
Guitar .up-|> ElectronicInstrument : <<implements>>

Piano .up-|> Instrument : <<implements>>
Piano .up-|> KeyboardInstrument : <<implements>>
hide empty members
@enduml